#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

DOTFILES_ROOT=$(pwd -P)

source script/_helpers

ensure_symlinks

enter_section "Installing brew packages"
find . -name brew.txt | \
    while read brewpacks ; \
    do print_info "brew install --quiet $(cat ${brewpacks})" && brew install --quiet $(cat "${brewpacks}") ; \
    done
exit_section

enter_section "Running installers"
# find the installers and run them iteratively
find . -name install.sh | while read installer ; do print_info "Running ${installer}" && source "${installer}" ; done
exit_section
